server:
  port: 8002
spring:
  application:
    name: service-oss

  profiles:
    active: dev
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tPZkpQ7hhzQAwSuu6C5
      keysecret: bsZxRHydEC6Xf7RGaY3INxYBk7MzEl
      bucketname: zhangr648-edu